feat: detect mouth centre for overlay
holistic-web/maskify pull request #7
Opened 2020-05-11 07:37 UTC by andrewlew1s

Completed:

- Set up Google Cloud Project & Credentials (in discord)
- Get facial data (mouth centre seems the most useful)
- Put in in cloud function
- Remove test.js

ToDo:

- Test and deploy firebase function (it worked as a test.js script)
- Integrate with UI

2020-05-12 09:29 UTC, fitzhavey requested changes

2020-05-12 09:29 UTC, michaelfitzhavey commented on cloud-functions/functions/index.js
> +		console.log(JSON.stringify(result, null, '\t'));
Let's remove this line before deploying

2020-05-12 09:29 UTC, michaelfitzhavey commented on website/src/components/ImageMasker.vue
> +						max="2"
Why have we modified `max`?

2020-05-12 09:29 UTC, michaelfitzhavey commented on website/src/components/ImageMasker.vue
> +			type: Object, // TODO: switch type to object and use facial recognition data to add mask
We should remove the (now incorrect) comment

2020-05-12 09:29 UTC, michaelfitzhavey commented on website/src/components/ImageMasker.vue
> +				leftOffset: 1,
These default values are useful for if no face is found, why are we deleting them?

2020-05-12 09:29 UTC, michaelfitzhavey commented on website/src/components/ImageMasker.vue
>  		drawMask(mask) {
I think the drawmask functionality should remain as it was, perhaps we need a computed value `defaultMaskPosition` that uses `imageData`.

It's important we don't confuse the functionality of working out the bounding box and rotation of the ideal mask with the functionality of overlaying one PNG on another (what `drawMask` currently does).

2020-05-12 09:29 UTC, michaelfitzhavey commented on website/src/components/ImageMasker.vue
> -				this.imageSize * this.maskSizing.leftOffset,
`this.imageSize` matters, don't delete all references to it!

2020-05-13 00:16 UTC, michaelfitzhavey commented
You should run `git pull origin master` as https://github.com/holistic-web/maskify/pull/8 has been merged.

2020-05-20 03:04 UTC, michaelfitzhavey commented
This PR may be out of date once this is merged: https://github.com/holistic-web/maskify/pull/11

2022-11-15 00:30 UTC, closed without merging